### ISSUE TITLE
Java causing problem in input using scanner

### ISSUE THREAD

**Issue by musawershah1598** [shawon100/Online-Compiler#7]
When ever i run the code with below command having scanner in code.
`java Hello < input.txt`
My input file have all the inputs specify for each scanner it giving me the following error.
`
Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at Example.main(Example.java:7)
`

**Comment by shawon100** [comment]
Rename your class as Main.  Import all kinds of library that supports Scanner.

**Comment by musawershah1598** [comment]
Thank you very much
